### ISSUE TITLE
Config NullPointerException

### ISSUE THREAD

**Issue by katur239** [CobbleWorksMC/CobbleWorks#2]
Setting enabledSpawner=false causes a crash during postinit.

```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CobbleWorks (cobbleworks)
Caused by: java.lang.NullPointerException
	at curtis.Cobbleworks.CommonProxy.postInit(CommonProxy.java:158)
	at curtis.Cobbleworks.ClientProxy.postInit(ClientProxy.java:69)
	at curtis.Cobbleworks.Cobbleworks.postInit(Cobbleworks.java:40)
```

**Comment by CobbleWorksMC** [comment]
Sorry for the late response, I'll look into this. It's probably another case of I did something dumb.

**Comment by CobbleWorksMC** [comment]
Yeah I totally forgot to add a check to make sure the spawner config option was enabled before registering vanilla mobs for it. Since the mod does not register the spawner if you do not enable it, you can't really tell it what to spawn if you don't enable it.

Next update will contain the fix, or you can clone the repo and build it yourself if you need it now.
